### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by macpac59** [CDrummond/lms-mipmixer#2]
Hi Craig,

This seems to be an interesting alternative to the Sugarcube Spicefly as well as the standard MusicIP mixer. Does it only work with https://github.com/CDrummond/musicip or can it be used with the installation described in https://forums.slimdevices.com/showthread.php?106958-Success-MusicIP-and-Spicefly-Sugarcube-running-on-Raspberry-Pi? 

In any way, how can it be installed?

Regards
macpac

**Comment by CDrummond** [comment]
[https://github.com/CDrummond/musicip](https://github.com/CDrummond/musicip) is just my notes, scripts, etc, that I use to get MusicIP working for my particular setup - it is not required for this plugin.

To use this plugin, you can either manually install the ZIP file or use [my repo](https://raw.githubusercontent.com/CDrummond/lms-plugins/master/repo.xml)
